spring:
  profiles:
    include: oauth  

  session:
    store-type: jdbc

  jpa:
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mustache:
    prefix: file:///app/repo/justsite/src/main/resources/templates/
    cache: false

  resources:
    static-locations: file:///app/repo/justsite/src/main/resources/static

logging:
  level:
    org.springframework: info

--- #구분
spring:
  profiles: real

--- #구분
spring:
  profiles: local

  h2:
    console:
      enabled: true

  mustache:
    prefix: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\templates\
    cache: false

  resources:
    static-locations: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\static
