--- #구분
spring:
  mustache:
    suffix: .html

  session:
    store-type: jdbc

  jpa:
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

--- #구분
spring:
  profiles:
    active: local
    include: oauth

  h2:
    console:
      enabled: true

  mustache:
    prefix: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\templates
    cache: false
#    prefix: classpath:\templates\

  resources:
    static-locations: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\static
#    static-locations: classpath:\static\
