spring:
  profiles:
    include: oauth  

  session:
    store-type: jdbc

  jpa:
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{visitorIp}] [%thread] %-5level %logger{36} – %msg%n"

--- #구분
spring:
  profiles: real

  mustache:
    prefix: file:///app/repo/justsite/src/main/resources/templates/
    cache: false

  resources:
    static-locations: file:///app/repo/justsite/src/main/resources/static

--- #구분
spring:
  profiles: local

  mustache:
    prefix: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\templates\
    cache: false

  resources:
    static-locations: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\static
