--- #구분
spring:
  mustache:
    suffix: .html


#  devtools:
#    livereload:
#      enabled: true
#
#  freemarker:
#    cache: false

--- #구분
spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  resources:
    static-locations: file:///C:\Users\wjdrn\IdeaProjects\justsite\src\main\resources\static